import type {
  Invoice,
  Mailbox,
  FolderMapping,
  DriveConfig,
  Business,
  Revenue,
} from "./types";
import { DEFAULT_FEE_RATES, EMPTY_TX_COUNTS } from "./types";

export const mockBusinesses: Business[] = [
  { id: "biz-link", name: "Link", color: "#7c9cff", processor: "Stripe" },
  { id: "biz-ify", name: "Ify", color: "#f59e0b", processor: "Stripe" },
];

export const mockRevenues: Revenue[] = [
  {
    id: "rev-link-202605",
    businessId: "biz-link",
    month: "2026-05",
    processor: "Stripe",
    currency: "CHF",
    capturedAmount: 48_500.0,
    fees: 1_456.5,
    rollingReservePercent: 10,
    rollingReserveMonths: 3,
    releasedAt: null,
    validatedAt: null,
    notes: "Volume normal, légère hausse vs avril.",
    countryBreakdown: [
      { country: "CH", amount: 18_200.0 },
      { country: "FR", amount: 12_400.0 },
      { country: "DE", amount: 9_800.0 },
      { country: "IT", amount: 3_900.0 },
      { country: "US", amount: 4_200.0 },
    ],
    countryFileName: "link-mai-2026-pays.xlsx",
    txCounts: EMPTY_TX_COUNTS,
    feeRates: DEFAULT_FEE_RATES,
  },
  {
    id: "rev-link-202605-paypal",
    businessId: "biz-link",
    month: "2026-05",
    processor: "PayPal",
    currency: "CHF",
    capturedAmount: 12_800.0,
    fees: 512.0,
    rollingReservePercent: 0,
    rollingReserveMonths: 0,
    releasedAt: null,
    validatedAt: null,
    notes: "Second processeur sur Link — pas de reserve sur PayPal.",
    countryBreakdown: [
      { country: "CH", amount: 5_100.0 },
      { country: "FR", amount: 3_400.0 },
      { country: "DE", amount: 2_500.0 },
      { country: "US", amount: 1_800.0 },
    ],
    countryFileName: "link-mai-2026-paypal-pays.xlsx",
    txCounts: EMPTY_TX_COUNTS,
    feeRates: DEFAULT_FEE_RATES,
  },
  {
    id: "rev-ify-202605",
    businessId: "biz-ify",
    month: "2026-05",
    processor: "Stripe",
    currency: "CHF",
    capturedAmount: 22_300.0,
    fees: 781.05,
    rollingReservePercent: 10,
    rollingReserveMonths: 6,
    releasedAt: null,
    validatedAt: null,
    countryBreakdown: [
      { country: "CH", amount: 6_400.0 },
      { country: "FR", amount: 5_100.0 },
      { country: "DE", amount: 4_700.0 },
      { country: "BE", amount: 2_200.0 },
      { country: "US", amount: 3_900.0 },
    ],
    countryFileName: "ify-mai-2026-pays.xlsx",
    txCounts: EMPTY_TX_COUNTS,
    feeRates: DEFAULT_FEE_RATES,
  },
  {
    id: "rev-link-202604",
    businessId: "biz-link",
    month: "2026-04",
    processor: "Stripe",
    currency: "CHF",
    capturedAmount: 42_100.0,
    fees: 1_263.0,
    rollingReservePercent: 10,
    rollingReserveMonths: 3,
    releasedAt: null,
    validatedAt: "2026-05-02T08:30:00.000Z",
    countryBreakdown: [
      { country: "CH", amount: 16_800.0 },
      { country: "FR", amount: 10_900.0 },
      { country: "DE", amount: 8_500.0 },
      { country: "US", amount: 5_900.0 },
    ],
    countryFileName: "link-avril-2026-pays.xlsx",
    txCounts: EMPTY_TX_COUNTS,
    feeRates: DEFAULT_FEE_RATES,
  },
];

const EMPTY_MAILBOX_OAUTH = {
  syncEnabled: true,
  oauthClientId: null,
  hasOauthSecret: false,
  oauthUserEmail: null,
  oauthExpiresAt: null,
  oauthScope: null,
  hasRefreshToken: false,
};

export const mockMailboxes: Mailbox[] = [
  {
    id: "mb-1",
    email: "comptabilite@bim-commune.ch",
    provider: "gmail",
    connected: false,
    invoicesFound: 0,
    lastSync: null,
    ...EMPTY_MAILBOX_OAUTH,
  },
  {
    id: "mb-2",
    email: "factures@bim-commune.ch",
    provider: "gmail",
    connected: false,
    invoicesFound: 0,
    lastSync: null,
    ...EMPTY_MAILBOX_OAUTH,
  },
  {
    id: "mb-3",
    email: "achat@bim-commune.ch",
    provider: "outlook",
    connected: false,
    invoicesFound: 0,
    lastSync: null,
    ...EMPTY_MAILBOX_OAUTH,
  },
];

// Code = abréviation utilisée dans le nom du fichier final
// (ex: "22.05.26 - Runpod - TECH"). Tu peux le changer dans Classement comptable.
export const mockFolderMappings: FolderMapping[] = [
  {
    id: "fm-proc",
    creditorPattern: "Stripe|PayPal|Adyen|Square|SumUp|Worldline|Twint",
    folderCode: "PROC",
    folderLabel: "Commission et charges du processeur de paiement",
  },
  {
    id: "fm-sal",
    creditorPattern: "Salaire|AVS|LPP|Caisse|Suva|Assurance perte de gain",
    folderCode: "SAL",
    folderLabel: "Salaires & charges sociales",
  },
  {
    id: "fm-mkt",
    creditorPattern: "Meta|Google Ads|LinkedIn|TikTok|Mailchimp|Brevo|HubSpot",
    folderCode: "MKT",
    folderLabel: "Marketing & Publicité",
  },
  {
    id: "fm-tech",
    creditorPattern: "Runpod|OpenAI|Anthropic|AWS|GCP|Azure|Vercel|GitHub|Notion|Figma|Slack|Linear",
    folderCode: "TECH",
    folderLabel: "Charges logicielles, R&D & Technologie",
  },
  {
    id: "fm-loc",
    creditorPattern: "Loyer|Régie|SIG|Romande Energie|Services Industriels|Eau",
    folderCode: "LOC",
    folderLabel: "Charges de locaux",
  },
  {
    id: "fm-adm",
    creditorPattern: "Swisscom|Sunrise|Salt|La Poste|CFF|Office Suisse|Migros|Coop|Fiduciaire|Comptable",
    folderCode: "ADM",
    folderLabel: "Administration",
  },
  {
    id: "fm-ass",
    creditorPattern: "Helvetia|Vaudoise|Bâloise|Zurich|Mobilière|AXA|Impôts|TVA|Administration fiscale",
    folderCode: "ASS",
    folderLabel: "Assurances & Taxes",
  },
  {
    id: "fm-nc",
    creditorPattern: "(jamais — réservé au tri manuel)",
    folderCode: "NC",
    folderLabel: "Charges non classées",
    notes:
      "Catégorie de dernier recours. Ne pas l'attribuer automatiquement — uniquement via l'onglet À traiter manuellement, quand aucune autre catégorie ne convient.",
  },
];

export const FALLBACK_CATEGORY_ID = "fm-nc";

export const mockDrive: DriveConfig = {
  provider: null,
  connected: false,
  rootPath: null,
};

const today = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return iso(d);
};

export const mockInvoices: Invoice[] = [
  {
    id: "inv-1",
    subject: "Your Runpod invoice — May 2026",
    fromEmail: "billing@runpod.io",
    mailbox: "comptabilite@bim-commune.ch",
    receivedAt: daysAgo(1),
    creditor: "Runpod",
    invoiceDate: "2026-05-22",
    amount: 124.5,
    currency: "USD",
    folderCode: "TECH",
    folderLabel: "Charges logicielles, R&D & Technologie",
    finalName: "22.05.26 - Runpod - TECH",
    drivePath: "/Comptabilité/2026/05/TECH - Charges logicielles, R&D & Technologie/22.05.26 - Runpod - TECH.pdf",
    status: "matched",
    excelRowMatched: 47,
    attachment: { name: "runpod-2026-05.pdf", sizeBytes: 218_400, pages: 1 },
  },
  {
    id: "inv-2",
    subject: "Facture Swisscom 05.2026",
    fromEmail: "no-reply@swisscom.ch",
    mailbox: "factures@bim-commune.ch",
    receivedAt: daysAgo(3),
    creditor: "Swisscom",
    invoiceDate: "2026-05-15",
    amount: 89.0,
    currency: "CHF",
    folderCode: "ADM",
    folderLabel: "Administration",
    finalName: "15.05.26 - Swisscom - ADM",
    drivePath: "/Comptabilité/2026/05/ADM - Administration/15.05.26 - Swisscom - ADM.pdf",
    status: "matched",
    excelRowMatched: 52,
    attachment: { name: "swisscom-05-2026.pdf", sizeBytes: 304_120, pages: 2 },
  },
  {
    id: "inv-3",
    subject: "OpenAI receipt — subscription",
    fromEmail: "billing@openai.com",
    mailbox: "comptabilite@bim-commune.ch",
    receivedAt: daysAgo(4),
    creditor: "OpenAI",
    invoiceDate: "2026-05-10",
    amount: 200.0,
    currency: "USD",
    folderCode: "TECH",
    folderLabel: "Charges logicielles, R&D & Technologie",
    finalName: "10.05.26 - OpenAI - TECH",
    drivePath: "/Comptabilité/2026/05/TECH - Charges logicielles, R&D & Technologie/10.05.26 - OpenAI - TECH.pdf",
    status: "uploaded",
    excelRowMatched: null,
    attachment: { name: "openai-receipt-may.pdf", sizeBytes: 87_200, pages: 1 },
  },
  {
    id: "inv-4",
    subject: "Stripe — frais de transaction mai",
    fromEmail: "receipts@stripe.com",
    mailbox: "comptabilite@bim-commune.ch",
    receivedAt: daysAgo(2),
    creditor: "Stripe",
    invoiceDate: "2026-05-18",
    amount: 312.7,
    currency: "CHF",
    folderCode: "PROC",
    folderLabel: "Commission et charges du processeur de paiement",
    finalName: "18.05.26 - Stripe - PROC",
    drivePath: "/Comptabilité/2026/05/PROC - Commission et charges du processeur de paiement/18.05.26 - Stripe - PROC.pdf",
    status: "renamed",
    excelRowMatched: null,
    attachment: { name: "stripe-mai-2026.pdf", sizeBytes: 95_800, pages: 1 },
  },
  {
    id: "inv-5",
    subject: "Facture inconnue — fournisseur local",
    fromEmail: "compta@boulangerie-meyer.ch",
    mailbox: "factures@bim-commune.ch",
    receivedAt: daysAgo(1),
    creditor: "Boulangerie Meyer",
    invoiceDate: "2026-05-19",
    amount: 42.5,
    currency: "CHF",
    folderCode: null,
    folderLabel: null,
    finalName: null,
    drivePath: null,
    status: "manual",
    excelRowMatched: null,
    attachment: { name: "facture-meyer-mai.pdf", sizeBytes: 64_100, pages: 1 },
  },
  {
    id: "inv-6",
    subject: "Receipt #A-2026-0451",
    fromEmail: "billing@unknownvendor.example",
    mailbox: "achat@bim-commune.ch",
    receivedAt: daysAgo(0),
    creditor: null,
    invoiceDate: null,
    amount: null,
    currency: null,
    folderCode: null,
    folderLabel: null,
    finalName: null,
    drivePath: null,
    status: "analyzing",
    excelRowMatched: null,
    attachment: { name: "receipt-A-2026-0451.pdf", sizeBytes: 110_000, pages: 1 },
  },
  {
    id: "inv-7",
    subject: "Meta Ads — campagne mai",
    fromEmail: "billing@meta.com",
    mailbox: "comptabilite@bim-commune.ch",
    receivedAt: daysAgo(5),
    creditor: "Meta",
    invoiceDate: "2026-05-12",
    amount: 540.0,
    currency: "CHF",
    folderCode: "MKT",
    folderLabel: "Marketing & Publicité",
    finalName: "12.05.26 - Meta - MKT",
    drivePath: "/Comptabilité/2026/05/MKT - Marketing & Publicité/12.05.26 - Meta - MKT.pdf",
    status: "classified",
    excelRowMatched: null,
    attachment: { name: "meta-ads-mai.pdf", sizeBytes: 71_300, pages: 1 },
  },
  {
    id: "inv-8",
    subject: "Loyer mai 2026 — Régie Dupont",
    fromEmail: "facturation@regie-dupont.ch",
    mailbox: "factures@bim-commune.ch",
    receivedAt: daysAgo(15),
    creditor: "Régie Dupont",
    invoiceDate: "2026-05-01",
    amount: 2400.0,
    currency: "CHF",
    folderCode: "LOC",
    folderLabel: "Charges de locaux",
    finalName: "01.05.26 - Régie Dupont - LOC",
    drivePath: "/Comptabilité/2026/05/LOC - Charges de locaux/01.05.26 - Régie Dupont - LOC.pdf",
    status: "uploaded",
    excelRowMatched: null,
    attachment: { name: "loyer-mai-2026.pdf", sizeBytes: 132_000, pages: 1 },
  },
  // Une facture du mois précédent pour démontrer le filtre mois
  {
    id: "inv-9",
    subject: "Helvetia — prime trimestrielle",
    fromEmail: "no-reply@helvetia.ch",
    mailbox: "comptabilite@bim-commune.ch",
    receivedAt: daysAgo(35),
    creditor: "Helvetia",
    invoiceDate: "2026-04-15",
    amount: 480.0,
    currency: "CHF",
    folderCode: "ASS",
    folderLabel: "Assurances & Taxes",
    finalName: "15.04.26 - Helvetia - ASS",
    drivePath: "/Comptabilité/2026/04/ASS - Assurances & Taxes/15.04.26 - Helvetia - ASS.pdf",
    status: "uploaded",
    excelRowMatched: null,
    attachment: { name: "helvetia-trim-q2.pdf", sizeBytes: 88_400, pages: 1 },
  },
];

export type AppData = {
  mailboxes: Mailbox[];
  invoices: Invoice[];
  mappings: FolderMapping[];
  drive: DriveConfig;
  businesses: Business[];
  revenues: Revenue[];
};

export const initialData: AppData = {
  mailboxes: mockMailboxes,
  invoices: mockInvoices,
  mappings: mockFolderMappings,
  drive: mockDrive,
  businesses: mockBusinesses,
  revenues: mockRevenues,
};
